name: Cache

on:
  deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Token
        env:
          TOKEN: ${{ secrets.TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
        run: |
